language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.2
env:
  - MIX_ENV=test
otp_release:
  - 19.3
  - 20.1
script: mix coveralls.travis
matrix:
  allow_failures:
    - elixir: 1.3.4
      otp_release: 20.1
